apiVersion: apps/v1
kind: Deployment
metadata:
  name: vth-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: nginx
