apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: sandbox
  name: nginx
  namespace: prod
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
